Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="151" judge-id="99" status="SE" scoring="ACM" run-tests="1" contest-id="3203" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>f63ea382-3f71-486a-ac00-16e7befdcef2</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="281" real-time="295" max-memory-used="18698240" >
  <program-stats-str>{ utime=270, stime=11, ptime=281, rtime=295, maxvsz=18698240, maxrss=19378176, nvcsw=1, nivcsw=42 }</program-stats-str>
      <input size="8">2
5
0
2
</input>
      <output size="0"></output>
      <stderr size="270">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000151&quot;, line 5, in &lt;module&gt;
    n = a
NameError: name 'a' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
