Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="227" judge-id="37" status="SE" scoring="ACM" run-tests="2" contest-id="3103" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="2" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>eeae27f7-f550-492b-b5a2-0d0455a74233</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="OK" time="27" real-time="34" max-memory-used="307200"  checker-comment="ok Answer NO" >
  <program-stats-str>{ utime=27, stime=0, ptime=27, rtime=34, maxvsz=307200, maxrss=6402048, nvcsw=1, nivcsw=4 }</program-stats-str>
  <checker-stats-str>{ utime=0, stime=0, ptime=0, rtime=1, maxvsz=462848, maxrss=2654208, nvcsw=1, nivcsw=1 }</checker-stats-str>
      <input size="16">4 3
1 2
2 3
1 3
</input>
      <output size="3">NO
</output>
      <correct size="3">NO
</correct>
      <stderr size="0"></stderr>
      <checker size="14">ok Answer NO 
</checker>
    </test>
    <test num="2" status="SE" time="285" real-time="312" max-memory-used="18702336" >
  <program-stats-str>{ utime=270, stime=15, ptime=285, rtime=312, maxvsz=18702336, maxrss=19566592, nvcsw=1, nivcsw=47 }</program-stats-str>
      <input size="4">5 0
</input>
      <output size="0"></output>
      <stderr size="331">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000227&quot;, line 26, in &lt;module&gt;
    dfs(i, 1)
  File &quot;./000227&quot;, line 17, in dfs
    for u in ar[v]:
IndexError: list index out of range
</stderr>
    </test>
  </tests>
</testing-report>
