Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="48" judge-id="49" status="SE" scoring="ACM" run-tests="1" contest-id="3206" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>738ad3e9-6f2e-4929-b6fb-dbdac4147fda</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="281" real-time="323" max-memory-used="32251904" >
  <program-stats-str>{ utime=251, stime=30, ptime=281, rtime=323, maxvsz=32251904, maxrss=19124224, nvcsw=2, nivcsw=40 }</program-stats-str>
      <input size="23">1
Trifonov Roman 4 1 4
</input>
      <output size="0"></output>
      <stderr size="284">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000048&quot;, line 11, in &lt;module&gt;
    a = int(O(3))
TypeError: 'str' object is not callable
</stderr>
    </test>
  </tests>
</testing-report>
