Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="228" judge-id="133" status="SE" scoring="ACM" run-tests="1" contest-id="3206" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>6f5e2186-d462-47dd-b114-20fb9ef1b346</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="282" real-time="310" max-memory-used="32251904" >
  <program-stats-str>{ utime=266, stime=16, ptime=282, rtime=310, maxvsz=32251904, maxrss=19259392, nvcsw=1, nivcsw=54 }</program-stats-str>
      <input size="2">f
</input>
      <output size="0"></output>
      <stderr size="277">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000228&quot;, line 7, in &lt;module&gt;
    print(YES)
NameError: name 'YES' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
