Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="236" judge-id="5" status="SE" scoring="ACM" run-tests="1" contest-id="3204" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>b533dc21-1cae-4ced-9d0c-45e70042443c</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="292" real-time="313" max-memory-used="18698240" >
  <program-stats-str>{ utime=264, stime=28, ptime=292, rtime=313, maxvsz=18698240, maxrss=19124224, nvcsw=1, nivcsw=43 }</program-stats-str>
      <input size="37">165 163 160 160 157 157 155 154 
162
</input>
      <output size="0"></output>
      <stderr size="284">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000236&quot;, line 10, in &lt;module&gt;
    while f&lt;=len(a)-1:
NameError: name 'f' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
