Content-type: text/xml

<?xml version="1.0" encoding="utf-8"?>
<testing-report run-id="163" judge-id="164" status="SE" scoring="ACM" run-tests="1" contest-id="3200" real-time-available="yes" max-memory-used-available="yes" correct-available="yes" failed-test="1" time-limit-ms="2000" real-time-limit-ms="5000" marked-flag="no" >
  <uuid>f8b1ef65-0bf0-4059-944b-b631e06f22a3</uuid>
  <host>localhost.localdomain</host>
  <cpu-model>Intel(R) Pentium(R) CPU 3550M @ 2.30GHz</cpu-model>
  <cpu-mhz>2294.738</cpu-mhz>
  <compiler_output></compiler_output>
  <tests>
    <test num="1" status="SE" time="284" real-time="301" max-memory-used="18698240" >
  <program-stats-str>{ utime=258, stime=26, ptime=284, rtime=301, maxvsz=18698240, maxrss=19226624, nvcsw=1, nivcsw=40 }</program-stats-str>
      <input size="2">7
</input>
      <output size="0"></output>
      <stderr size="271">Can't open '/usr/share/abrt/conf.d/plugins/python3.conf': Operation not permitted
Can't open '/etc/abrt/plugins/python3.conf': Operation not permitted
Traceback (most recent call last):
  File &quot;./000163&quot;, line 5, in &lt;module&gt;
    a=a//2
NameError: name 'a' is not defined
</stderr>
    </test>
  </tests>
</testing-report>
